import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../app/styles/main.scss";
import Header from "./components/layout/Header";

const roboto = Roboto({
  weight: ["400", "700"], // weights you need
  subsets: ["latin"], // subset for your language
  display: "swap", // optional, recommended
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
