import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../app/styles/main.scss";
import Header from "./components/layout/Header";

const roboto = Roboto({
  weight: ["200", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Header></Header>
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
